Vagrant.configure("2") do |config|
  config.vm.box = "fedora/37-cloud-base"
  config.vm.box_version = "37.20221105.0"
  config.vm.provider "libvirt" do |vb|
    vb.memory = "1024"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.groups = {
      "vagrant" => [
         "default"
            ]
          }
  end
end
